stages:
  - test
  - create-new-tag
  - deploy

test:
  stage: test
  image: node:8.11.1
  except:
    - tags
  cache:
    paths:
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn lint
    - yarn tsc
    - rm -rf ./lib
    - yarn test.storybook

create-new-tag:
  stage: deploy
  image: node:8.11.1
  when: manual
  only:
    - master
  variables:
    CI_REPOSITORY_URL: https://$GIT_ACCESS_USER:$GIT_ACCESS_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
  before_script:
    - git config --global user.email "liviu.ignat@everreal.co"
    - git config --global user.name "CI Deployment Bot"
  script:
    - npm version patch  -m "%s"
    - git push --follow-tags $CI_REPOSITORY_URL HEAD:$CI_COMMIT_REF_NAME

publish-npm:
  stage: deploy
  image: node:8.11.1
  only:
    - tags
  before_script:
    - apt-get update -qq
    - apt-get -qq install rsync
    - git config --global user.email "liviu.ignat@everreal.co"
    - git config --global user.name "CI Deployment Bot"
    - npm update npm
  script:
    - echo "running 'git pull $CI_REPOSITORY_URL HEAD HEAD:$CI_COMMIT_REF_NAME'"
    - cat package.json | grep version
    - yarn install
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>${HOME}/.npmrc
    - cat ${HOME}/.npmrc
    - npm run build
    - npm run publish-package
